name: 'changed-objects'
description: 'Get changed objects'
inputs:
  added:
    description: 'Show added objects'
    required: false
    default: 'false'
  deleted:
    description: 'Show deleted objects'
    required: false
    default: 'false'
  modified:
    description: 'Show modified objects'
    required: false
    default: 'false'
outputs:
  changed:
    description: 'Changed objects'
runs:
  using: 'docker'
  image: 'Dockerfile'
